Model:
    CharSet: [' ', 加, 三, '7', 九, 二, '6', 去, 五, '0', '=', '9', 六, x, '3', 以, 四, '-',
        七, 零, 称, 乘, '8', 一, '1', '2', 八, '5', +, '4', 上, 减]
    ImageChannel: 3
    ImageHeight: 32
    ImageWidth: -1
    Word: false
System:
    Allow_Ext: [jpg, jpeg, png, bmp]
    GPU: true
    GPU_ID: 0
    Path: .\train_images\linxia\
    Project: linxia
    Val: 0.06
Train:
    BATCH_SIZE: 128
    CNN: {NAME: ddddocr}
    DROPOUT: 0.3
    LR: 0.01
    OPTIMIZER: SGD
    SAVE_CHECKPOINTS_STEP: 2000
    TARGET: {Accuracy: 0.9, Cost: 0.05, Epoch: 20}
    TEST_BATCH_SIZE: 128
    TEST_STEP: 16
